In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype='int16')
print(a)
a.shape

[1 2 3]


(3,)

In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Shape
# a.ndim
b.ndim

2

In [5]:
# GetShape 
b.shape

(2, 3)

In [6]:
# Get Type 
a.dtype

dtype('int16')

In [7]:
# Get item Size in Bytes
a.itemsize

2

In [8]:
# Get total Size of array
a.nbytes 

6

## Accessing/Changing specific elements, row, columns, etc

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
#  Get a specific element [r,c]
a[1, 5]

13

In [11]:
#  Get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
a[:,2]

array([ 3, 10])

In [13]:
# Fancy Retrieval [startindex, endindex: stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [14]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [15]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [16]:
b = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
#  Get a specific element (work outside in)
b[0, 1, 1]

4

In [18]:
b[0]

array([[1, 2],
       [3, 4]])

In [19]:
#  all zeros matrix
np.zeros((2,3,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [20]:
#  All 1s Matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [21]:
# Any other Number
np.full((2,2),99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [22]:
# Any other number(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [23]:
# random decimal numbers
np.random.rand(4,2)

array([[0.4502992 , 0.87557015],
       [0.99642145, 0.9180088 ],
       [0.38469999, 0.48946862],
       [0.97276702, 0.52937395]])

In [24]:
# Random Integer values
np.random.randint(-2,7, size=(3,3))

array([[5, 5, 2],
       [4, 0, 3],
       [2, 0, 2]])

In [25]:
#  Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
#  Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis = 0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [27]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be careful when copying arrays! 

In [28]:
a = np.array([1,2,3])
b = a.copy() 
# copy function just copies the elemensts instead of b pointing to a
print(b)
b[0]=100
print(a)

[1 2 3]
[1 2 3]


## Mathematics

In [29]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [30]:
a+2

array([3, 4, 5, 6])

In [31]:
a-2

array([-1,  0,  1,  2])

## 

In [32]:
a*2

array([2, 4, 6, 8])

In [33]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [34]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [35]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [36]:
#  taking the trigonometric values of all elements 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### Linear Algebra 

In [37]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [38]:
# Finding the determinant
c = np.identity(3)

np.linalg.det(c)

1.0

In [39]:
np.linalg.inv(c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Statistics 

In [41]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.min(stats, axis = 1)

array([1, 4])

In [43]:
np.max(stats)

6

In [48]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [51]:
before = np.array([[1,2,3,4],[5,6,7,8]])
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [54]:
#  Vertically stacking vectors - size should be same 
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [57]:
#  Horizontal stacking vectors - rows should be same 
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

##### Loading data from file 

In [61]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32') # it reads as float  
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean masking and avdanced indexing

In [64]:
filedata>=50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [65]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [69]:
# Can index with a list in numpy 
a = np.array([1,2,3,4,5,6,7,8,9])
a[[0,2,3,4]]

array([1, 3, 4, 5])

In [76]:
print(filedata)
np.any(filedata > 50)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


True

In [77]:
(~((filedata>50) & (filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [78]:
filedata[((filedata>10)&(filedata<18))]

array([13, 11, 12, 11, 12, 11, 11])